import os
import pandas as pd

# Point to the folder where your file is stored
folder_path = r"C:\Shanmukha\Amol-Project\MainData2"



# Read CSV file
df = pd.read_csv(os.path.join(folder_path, "Standardize_Site_Name_Cleaned.csv"))

# Define replacements
replacements = {
    "aiims": "All India Institute Of Medical Sciences",
    "all institute of medical sciences": "All India Institute Of Medical Sciences",
    "apollo": "Apollo Hospitals",
    "khudadad": "Shri Khudadad Dunga Ji Government Ayurved Hospital",
    "khudad": "Shri Khudadad Dunga Ji Government Ayurved Hospital",
    
    

    "arignar anna govt hospital of n medicine and homoeopathy": "Arignar Anna government hospital",
    "arignar anna government hospital of n medicine": "Arignar Anna government hospital",

    "kalinga institute of medical sciences": "Kalinga Institute of Medical Sciences",
    "kalinga institute of medical sciences(kims)": "Kalinga Institute of Medical Sciences",
    "sree chitra tirunal institute for medical sciences and technology (sctimst)": "Sree chitra tirunal institute for medical sciences and technology",
      
    "rishikul ayurvedic college"  : "rishikul ayurvedic college and hospital",
    "rishikul ayurveda college" : "rishikul ayurvedic college and hospital",
    "rishikul ayurvedic collage and hospital" : "rishikul ayurvedic college and hospital",
    "rishikul campus" : "rishikul ayurvedic college and hospital",

    "khemdas ayurveda hospital" : "khemdas ayurveda hospital",
    "khemdas ayurved hospital" : "khemdas ayurveda hospital",

    "kmc mangalore" : "kmc hospitals",
    "kmc hospitals" : "kmc hospitals",

    "sri jayachamarajendra institute of n medicine" : "sri jayachamarajendra institute of  medicine hospital",
    "sri jayachamarajendra institute of n medicine hospital" : "sri jayachamarajendra institute of  medicine hospital",

    "ipgt and ra gau jamnagr" : "ipgt and ra",
    "ipgt and ra" : "ipgt and ra",
    "pg hospital ipgt and ra jamnagar" : "ipgt and ra",
    "pg hospital ipgt and ra" : "ipgt and ra",

    "nair hospital dental college" : "nair hospital  and dental college",
    "nair hospital and dental college" : "nair hospital and dental college",

    "kasturba hospital manipal karnataka" : "kasturba hospital",
    "orthopaedics kasturba medical college" : "kasturba medical college",
    "manipal academy of higher education" : "manipal academy of higher education",
    "academic and administrative offices of manipal academy of higher education" : "manipal academy of higher education",
    "orthopaedics kasturba medical college" : "kasturba medical college",
    "kasturba medical college hospital" : "kasturba medical college and  hospital",
    "kasturba medical college and hosptial" : "kasturba medical college and hosptial",
    "kasturba medical collage" : "kasturba medical college",
    "mazumdhar shaw medical center" : "mazumdhar shaw medical center",
    "mazumdar shaw medical center" : "mazumdhar shaw medical center",
    "all institute of auyrveda" : "all institute of ayurveda",
    "tata memorial hospital" : "tata memorial centre and hospital",
    "tata memorial centre" : "tata memorial centre and hospital ",
    "lady harding medical college and associated hospitals" : "lady hardinge medical college and associated hospitals",
    "lady hardinge medical college" : "lady hardinge medical college and associated hospitals",
    "operation theatre in lady hardinge medical college and associate hospitals" : "lady hardinge medical college and associated hospitals",
    "k.l.e societys institute of dental sciences" : "kle societys institute of dental sciences",
    "dr harvansh singh judge institute of dental sciences and hospital panjab university chandigarh": "dr harvansh singh judge institute of dental sciences and hospital",
    "maulana azad medical college lok nayak hospital" : "maulana azad medical college and associated lok nayak hospital",
    "maulana azad medical college" : "maulana azad medical college and associated lok nayak hospital",
    "maulana azad medical college and associated lok nayak hospital" : "maulana azad medical college and associated lok nayak hospital",
    "indira gandhi institute of medical sciences patna bihar" :"indira gandhi institute of medical sciences",
    "indira gandhi institute of medical sciences patna" : "indira gandhi institute of medical sciences",
    "cardiology indira gandhi medical college" : "indira gandhi medical college",
    "indira gandhi medical college shimla" : " indira gandhi medical college",
    "indira gandhi medical college" : "indira gandhi medical college and associated hospitals",
    "indira gandhi institute of medical sciences sheikhpura patna" : "indira gandhi institute of medical sciences",
    "indira gandhi medical college shimla himachal pradesh" : "indira gandhi medical college",
    "indira gandhi institute of medical sciences sheikhpura" : "indira gandhi institute of medical sciences",
    "north eastern indira gandhi regional institute of health and medical science" : "indira gandhi regional institute of health and medical science",
    "indira gandhi medical college andhospital shimla" : "indira gandhi medical college and hospital",
    "north eastern indira gandhi regional institute of health and medical sciences" : "indira gandhi regional institute of health and medical sciences",
    "indira gandhi medical college shimla hp pin" : "indira gandhi medical college",
    "indira gandhi institute" : "indira gandhi institute of medical sciences",
    "indira gandhi medical college shimla h.p" : "indira gandhi medical college",
    "indira gandhi institute of dental sciences sri balaji vidhyapeeth" : "indira gandhi institute of dental sciences",
    "indira gandhi institute of dental sciences pondicherry" : "indira gandhi institute of dental sciences",
    "gis operation theatre of indira gandhi institute of medical science" : "indira gandhi institute of medical science",
    "indira gandhi medical college and research institute government hospital puducherry" : "indira gandhi medical college and research institute",
    "surgery indira gandhi government medical college" : "indira gandhi government medical college",
    "indira gandhi gov. general hospital and post graduate institute" : "indira gandhi governement general hospital and post graduate institute ",
    "national institute of ayurveda" : "national institute of ayurveda hospital",
    "kmc mangalore" : "kmc hospitals",
    "kmc hospitals" : "kmc hospitals",
    "pdayurved rugnalay sterling multispeciality hospital nigdi" : "ayurved rugnalaya and sterling multispeciality hospital",
    "ayurved rugnalaya and sterling multispeciality hospital nigadi pradhikaran" : "ayurved rugnalaya and sterling multispeciality hospital",
    "ayurved rugnalaya and sterling multispeciality hospital" : "ayurved rugnalaya and sterling multispeciality hospital",
    "amrita institute of medical sciences" : "amrita institute of medical sciences and research centre",
    "faculty of dental sciences sgt university" : "sgt university and denatl college",
    "sgt university" : "sgt university and dental college",
    "sgt dental college" : "sgt university and dental college",
    "neonatal intensive care unit shree krishna hospital" : "shree krishna hospital",
    "dr s.n.medical college jodhpur and associated hospitals" : "dr s.n.medical college and associated group of hospitals",
    "dr s.n.medical college and associated group of hospitals" : "dr s.n.medical college and associated group of hospitals",
    "sane guruji arogya kendra malwadi road hadapsar" : "sane guruji arogya kendra",
    "institute of dental studies and technology" : "institute of dental studies and technologies",
    "grant government medical college and sir j.j. group of hospitals" : "grant government medical college and sir jj group of hospitals",
    "pt. b.d. sharma pgims rohtak" : "pt. b.d. sharma pgims",
    "pt. b. d. sharma pgims rohtak" : "pt. b.d. sharma pgims",
    "department of physiotherapy opd guru jambheshwar university" : "department of physiotherapy guru jambheshwar university",
    "dr. d. p. rastogi central research institute of homoeopathy noida" : "dr. d p rastogi central research institute (h)",
    "regional research institute (h)" : "regional research institute(h)",
    "sri dharmasthala manjunatheshwara college of ayurveda and hospital hassan" : "sri dharmasthala manjunatheshwara college of ayurveda and hospital",
    "jss medical college hospital" : "jss hospital",
    "neonatal icu jss hospital" : "jss hospital",
    "sri ramachandra institute of higher education & research [sriher]" : "sri ramachandra institute of higher education and research",
    "post graduate institute of medical education and research chandigarh" : "post graduate institute of medical education and research ",
    "post graduate institute of medical education and research (pgimer) chandigarh" : "post graduate institute of medical education and research",
    "academic and administrative offices of manipal academy of higher education" : "manipal academy of higher education",
    "k.l.e societys institute of dental sciences" : "kle societys institute of dental sciences",
    "post graduate institute of medical education and research (pgimer) chandigarh" : "pgimer",
    "advanced cardiac centre pgimer" : "pgimer",
    "christianmedicalcollege" : "christian medical college and hospital",
    "christian medical college" : "christian medical college and hospital",
    "sri jayachamarajendra institute of n medicine" : "sri jayachamarajendra institute of  medicine hospital",
    "sri jayachamarajendra institute of n medicine hospital" : "sri jayachamarajendra institute of  medicine hospital",
    "rainbow childrenÃ¢â‚¬â„¢s hospital" : "rainbow childrens hospital",
    "national institute if siddha" : "national institute of siddha",
    "mams sumatibhai shah ayurved mahavidyalay malwadi hadapsar" : "sumatibhai shah ayurved college and hospital",
    "parul institute of ayurveda and research" : "parul ayurved hospital",
    "parul university,p.o.limda,tal. waghodia dist. vadodara gujarat" : "parul ayurved hospital",
    "sri sri college of ayurvedic science and research hospital" : "sri sri college of ayurvedic science and research hospital",
    "sri sri college of ayurvedic science and research" : "sri sri college of ayurvedic science and research hospital",
    "pandit madan mohan malviya cancer hospital" : "mahanama pandit madan mohan malaviya cancer centre",
    "karpaga vinayaga institute of medical sciences" : "karpaga vinayaga institute of medical sciences and research centre",
    "stavya spine hospital & research instiute" : "stavya spine hospital & research institute",
    "antenatal ward antenatal opd labour wch in jipmer" : "jipmer",
    "karpaga vinayaga institute of medical sciences" : "karpaga vinayaga institute of medical sciences and research centre",
    "antenatal ward antenatal opd labour wch in jipmer" : "jipmer",
    "command hospital ( eastern command)" : "command hospital",
    "justice k s hegde charitable hospital" : "justice ks hegde charitable hospital",
    "atal bihari vajpayee institute of medical sciences and dr ram manohar lohia hospital" :  "dr ram manohar lohia institute of medical sciences",
    "dr ram manohar lohia institute of science" :  "dr ram manohar lohia institute of medical sciences",
    "gmers medical college gotri" : "gmers medical college and hospital gotri",
    "neonatal intensive care unit shree krishna hospital" : "shree krishna hospital",
    "sri ramachandra institute of higher education & research [sriher]" : "sri ramachandra institute of higher education and research",
    "rishikul ayurveda college" : "rishikul ayurvedic college",
    "rishikul ayurvedic collage and hospital" : "rishikul ayurvedic college",
    "sree chitra tirunal institute for medical sciences and technology (sctimst)" : "sree chitra tirunal institute for medical sciences and technology",
    "department of physiotherapy opd guru jambheshwar university" : "department of physiotherapy guru jambheshwar university",
    "maharishi markandeshwar hospital" : "maharishi markandeshwar institute of medical sciences and research",
    ". and ipd of government ayurved college nagpur" : "government ayurved college and hospital nagpur",
    "balrog opd hon. annasaheb dange ayurvedic medical college ashta sangli" : "hon.shree annasaheb dange ayurved medical college and post graduation research centre ashta",
    "amrita institute of medical sciences" : "amrita institute of medical sciences and research centre",
    "kalinga institute of medical sciences" : "kalinga institute of medical sciences(kims)",
    "nicu sir t hospital" : "sir t hospital bhavnagar",
    "chettinad college of nursing" : "chettinad hospital and research institute",
    "mgm institute of physiotherapy" : "mgm dental college and hospital",
    "dr d y patil vidyapeeth" : "dr d y patil homoeopathic medical college",
    "nair hospital dental college" : "nair hospital and dental college",
    "sane guruji arogya kendra malwadi road hadapsar" : "sane guruji arogya kendra",
    "ms ramaiah medical teaching hospital" : "ramaiah medical college hospital",
    "opd no. shalya tantra department gurukul campus haridwar.hardwaruttaranchal" : "shalya tantra",
    "shalya tantra opd" : "shalya tantra",
    "king george medical university" : "king georges medical college",
    "jawaharlal institute of postgraduate medical education and research(jipmer)" : "jipmer",
    "antenatal ward antenatal opd labour wch in jipmer" : "jipmer",
    "jawaharlal institute of postgraduate medical education and research" : "jipmer",
    "national institute of ayurveda hospital" : "national institute of ayurveda",
    "advanced cardiac centre pgimer" : "pgimer",
    "k.l.e societys institute of dental sciences" : "kle societys institute of dental sciences",
    "shri b.m patil medical college hospital and reserch centre" : "shri b.m patil hospital",
    "ymt ayurvedic medical college and hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic college and hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "and ipd of ymt ayurvedic medical college" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "no shalakya tantra department ymt ayurvedic medical college and pg institute" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "dr g d pol foundation ymt ayurvedic medical college" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital.sector kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital sector kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "gd pol foundation ymt ayurvedic medical college and hospital kharghar" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college & hospital sector kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "no and ipd of shalakyatantra department of ymt ayurvedic medical hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital. sector kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "kayachikitsa department dr g. d. pol foundation ymt ayurvedic medical college & hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital kharghar" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "dr.g.d pol foundation ymt ayurvedic college and hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college and hospital sect kharghar navi" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic medical college & hospital pg institute ayurved samhita and siddhanta department" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic college and hospital sec kharghar" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "ymt ayurvedic college and hospital institutional area kharghar" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "dr. g. d. pol foundation ymt ayurvedic college and hospital" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    " dr. g.d. pol foundation ymt ayurvedic medical collage" : "dr.g.d pol foundation ymt ayurvedic college and hospital",
    "arogyashala rugnalaya nashik" : "arogyashala rugnalaya",
    "aarogyashala rugnalaya nashik" : "arogyashala rugnalaya",
    "aarogyashala rugnalaya ass ayurvedic mahavidyalaya" : "arogyashala rugnalaya",
    "arogyashala rugnalay nashik" : "arogyashala rugnalaya",
    "arogyashala rugnalaya kayachikitsa opd no" : "arogyashala rugnalaya",
    "arogyashala rugnalaya panchwati nashik" : "arogyashala rugnalaya",
    "arogyashala rugnalaya ganeshwadi panchavati nashik" : "arogyashala rugnalaya",
    "ayurved seva sangh arogyashala rugnalya nashik" : "arogyashala rugnalaya",
    "arogyashala national institute of ayurved" : "arogyashala national institute of ayurveda",
    "arogyashala hospital nia" : "arogyashala national institute of ayurveda",
    "aarogyashala national institute of ayurveda" : "arogyashala national institute of ayurveda",
    "arogyashala nia" : "arogyashala national institute of ayurveda",
    "kmc hospitals" : "kmc mangalore",
    "kmc hospital" : "kmc mangalore",
    "kmc hospitals mangalore" : "kmc mangalore",
    "kmc hospital ambedkar circle" : "kmc mangalore",
    "kmc ambedkar circle" : "kmc mangalore",
    "kmc hospital ambedkar circle mangalore" : "kmc mangalore",
    "kmc hospital ambedakar circle" : "kmc mangalore",
    "kmc hospital." : "kmc mangalore",
    "kmc hopsital jyoti circle" : "kmc mangalore",
    "kmc hospital attavara mangalore" : "kmc attavar hospital",
    "kmc hospital attavar" : "kmc attavar hospital",
    "kmc mangaluru" : "kmc mangalore",
    "kmc hospital mangaluru" : "kmc mangalore",
    "kmc hospital ambedkar circle mangalore karnataka phone no: . fax no:" : "kmc mangalore",
    "kmc hospital attavara mangalore" : "kmc mangalore",
    "kmc hospital ambedakar circle" : "kmc mangalore",
    "kmc hopsital jyoti circle" : "kmc mangalore",
    "kmc attavar hospital" : "kmc attavar hospital",
    "ayodidoss pandithar hospital" : "Ayothidas Pandithar Siddha Hospital",
    "ayodisoss panidhar hospital" : "Ayothidas Pandithar Siddha Hospital",
    "ayodidass pandithar hospital national institute of siddha" : "Ayothidas Pandithar Siddha Hospital",
    "n spinal injuries center" : "n spinal injuries centre",
    "n spinal injury center" : "n spinal injuries centre",
    "prosthetics and orthotics department n spinal injuries centre" : "n spinal injuries centre",
    "n spinal injury center vasant kunj" : "n spinal injuries centre",
    "n spinal injuries centre institute of rehabilitation sciences" : "n spinal injuries centre",
    "delhi pain management centre and n spinal injuries centre" : "n spinal injuries centre",
    "research department n spinal injuries centre" : "n spinal injuries centre",
    "m.s ramaih memorial hospital" : "ms ramaiah hospital",
    "ramaih indic specialty ayurveda" : "ms ramaiah hospital",
    "ms ramaiah medical teaching hospital" : "ms ramaiah hospital",
    "ms ramaiah medical college hospital" : "ms ramaiah hospital",
    "ms ramaiah medical college and hospitals" : "ms ramaiah hospital",
    "faculty of dental sciences ms ramaiah university of applied sceinces" : "ms ramaiah hospital",
    "ms ramaiah medical college" : "ms ramaiah hospital",
    "ms ramaiah memorial hospital" : "ms ramaiah hospital",
    "ms ramaiah college hospital" : "ms ramaiah hospital",
    "ms ramaiah hospital" : "ms ramaiah hospital",
    "ms ramaiah medical college and hospital" : "ms ramaiah hospital",
    "ms ramaiah hospitals" : "ms ramaiah hospital",
    "ms ramaiah medical college & teaching hospital" : "ms ramaiah hospital",
    "ms ramaiah memorial hospital dept of psychiatry" : "ms ramaiah hospital",
    "faculty of dental sciences ms ramaiah university of health sciences" : "ms ramaiah hospital",
    "v.s.p.m. dental college and research centre nagpur" : "v.s.p.m.s dental college and reasearch centre nagpur",
    "national institute of ayurveda hospital" : "national institute of ayurveda",
    "national institute of ayurveda jaipur rajasthan" : "national institute of ayurveda",
    "madhav vilas hospital national institute of ayurveda" : "national institute of ayurveda",
    "national institute of ayurveda hospital jaipur rajasthan" : "national institute of ayurveda",
    "pg dept of shalya tantra national institute of ayurveda" : "national institute of ayurveda",
    "hospital national institute of ayurveda" : "national institute of ayurveda",
    "national institute of ayurveda jaipur and ssbh kishanpole" : "national institute of ayurveda",
    "national institute of ayurveda deemed to be university" : "national institute of ayurveda",
    "national institute of ayurveda jaipur and associated hospitals" : "national institute of ayurveda",
    "national institute of ayurveda jaipur various camps" : "national institute of ayurveda",
    "hospital national institute of ayurveda deemed to be university" : "national institute of ayurveda",
    "national institute of ayurveda deemed university jaipur rajasthan" : "national institute of ayurveda",
    "national institute of ayurveda deemed to be university ( denovo)" : "national institute of ayurveda",
    "national institute of ayurveda deemed to be university jaipur rajasthan" : "national institute of ayurveda",
    "arogyashala national institute of ayurveda" : "national institute of ayurveda",
    "national institute of ayurveda deened to be university" : "national institute of ayurveda",
    "national institute of ayurveda campus hospital" : "national institute of ayurveda",
    "national institute of ayurveda (deemed to be university)" : "national institute of ayurveda",
    "national institute of ayurveda jaipur and related hospitals" : "national institute of ayurveda",
    "national institute of ayurveda hosital" : "national institute of ayurveda",
    "national institute of ayurveda college and hospital" : "national institute of ayurveda",
    "pg department of panchkarma opd national institute of ayurveda" : "national institute of ayurveda",
    "opd no. national institute of ayurveda hospital" : "national institute of ayurveda",
    "aarogyashala national institute of ayurveda" : "national institute of ayurveda",
    "and ipd of pg department of kayachikitsa national institute of ayurveda" : "national institute of ayurveda",
    "national institute of ayurveda& hospital" : "national institute of ayurveda",
    "national institute of ayurveda and hospital" : "national institute of ayurveda",
    "national institute of ayurveda hospital shalakya tantra department opd no." : "national institute of ayurveda",
    "national institute of ayurveda (nia)" : "national institute of ayurveda",
    "hospital of national institute of ayurveda" : "national institute of ayurveda",
    "national institute of ayurveda department swasthvritta evam yoga opd no" : "national institute of ayurveda",
    "national institute of ayurveda jaipur (rajasthan)" : "national institute of ayurveda",
    "coorg institute" : "coorg institute of dental sciences",
    "coorg institute of dental science" : "coorg institute of dental sciences",
    "coorg institute of dental sciences virajpet" : "coorg institute of dental sciences",
    "coorg institue of dental sciences virajpet,coorg karnataka" : "coorg institute of dental sciences",
    "no:,department of pedodontics and preventive dentistry coorg institute" : "coorg institute of dental sciences",
    "department of orthodontics and dentofacial orthopaedics coorg institute" : "coorg institute of dental sciences",
    "coorg institute of dental sciences maggula village virajpet p o kodagu district karnataka" : "coorg institute of dental sciences",
    "department of anaesthesiology and critical care ot dr pinnamaneni siddhartha institute" : "dr pinnamaneni siddhartha institute of medical sciences and research foundation",
    "dr pinnamaneni siddhartha institute of medical sciences and rf" : "dr pinnamaneni siddhartha institute of medical sciences and research foundation",
    "physiotherapy manipal college of health professions mahe" : "manipal college of health professions",
    "manipal college of health professions interdepartmental ( number is variable)" : "manipal college of health professions",
    "manipal college of health professionals" : "manipal college of health professions",
    "manipal college of health professions manipal academy of higher education manipal karnataka" : "manipal college of health professions",
    "clinical psychology manipal college of health professions" : "manipal college of health professions",
    "manipal college of health professions (mchp) mahe" : "manipal college of health professions",
    "manipal college of health professions (mchp)" : "manipal college of health professions",
    "manipal college of health professions manipal academy of higher education" : "manipal college of health professions",
    "manipal college of health professions mahe" : "manipal college of health professions",
    "manipal college of health profession" : "manipal college of health professions",
    "manipal college of health professions department of physiotherapy" : "manipal college of health professions",
    "optometry manipal college of health professions manipal academy of higher education" : "manipal college of health professions",
    "manipal college of health professions department of optometry" : "manipal college of health professions",
    "manipal college of health profssions" : "manipal college of health professions",
    "speech and hearing manipal college of health professions mahe" : "manipal college of health professions",
    "opd no shalya tantra department,gurukul campus uau haridwarhardwaruttaranchal" : "opd no. shalya tantra department gurukul campus haridwar.hardwaruttaranchal",
    "opd no. shalya tantra department gurukul campus haridwarhardwaruttaranchal" : "opd no. shalya tantra department gurukul campus haridwar.hardwaruttaranchal",
    "king george medical college" : "king george medical university",
    "king george medical university institutional ethics committee" : "king george medical university",
    "urology king george medical university" : "king george medical university",
    "king george medical university faculty of dental sciences" : "king george medical university",
    "king george medical university;queen marrys hospital" : "king george medical university",
    "chchatrapati shahu maharaj medical university and upgraded king george medical college(kgmc)" : "king george medical university",
    ". of surgical oncology csm medical university king george medical university" : "king george medical university",
    "oral pathology government dental college and hospital nagpur" : "government dental college and hospital nagpur",
    "periodontology government dental college and hospital nagpur" : "government dental college and hospital nagpur",
    "department of public health dentistry tamilnadu government dental college and hospital" : "tamil nadu government dental college and hospital",
    "madras medical college and tamilnadu government dental college hospital" : "tamil nadu government dental college and hospital",
    "the tamilnadu government dental college and hospital" : "tamil nadu government dental college and hospital",
    "dr.a v baliga home for senior citizen" : "a v baliga home for senior citizens",
    "dr av baliga ashraya home for senior citizens" : "a v baliga home for senior citizens",
    "king georges medical college" : "king george medical university",
    "king georges medical university" : "king george medical university",
    "king george hospital" : "king george medical university",
    "king george hospital visakhapatanam" : "king george medical university",
    "king georgeÃ¢â‚¬â„¢s medical university" : "king george medical university",
    "king georgeÃ¢â‚¬â„¢s medical university department of cardiology" : "king george medical university",
    "m/s king george hospital" : "king george medical university",
    "king georgeÃ¢â‚¬â„¢s medical university (kgmu)" : "king george medical university",
    "ost clinic department of psychiatry king georges medical university" : "king george medical university",
    "king george medical university institutional ethics committee" : "king george medical university",
    "king georges medical universitylucknowuttar pradesh" : "king george medical university",
    "urology king george medical university" : "king george medical university",
    "king george hospitals" : "king george medical university",
    "urology king georges medical university" : "king george medical university",
    "king george medical university faculty of dental sciences" : "king george medical university",
    "surgical gastroenterology king georgeÃ¢â‚¬â„¢s medical university" : "king george medical university",
    "king george hospital vishakapatnam" : "king george hospital vishakhapatanam",
    "king george s medical university" : "king george medical university",
    "andhra medical college king george hospital" : "king george hospital andhra medical collage",
    "king george memorial hospital" : "king george medical university",
    "pediatrics king george hospital" : "king george medical university",
    "surgery king georges medical university" : "king george medical university",
    "new king george hospital" : "king george medical university",
    ". of surgical oncology csm medical university king george medical university" : "king george medical university",
    "department of prosthodontics new dental building faculty of dental sciences king georges medical university" : "king george medical university",
    "sri ramachandra institute of higher education & research [sriher]" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher education and research (deemed to be university)" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher education and research sriher" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher eucation and research" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher education and researchsri ramachandra hospital" : "sri ramachandra institute of higher education and research",
    "research lab faculty of physiotherapy sri ramachandra institute of higher education and research" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher education and research institute" : "sri ramachandra institute of higher education and research",
    "sri ramachandra instituite of higher education and research" : "sri ramachandra institute of higher education and research",
    "sri ramchandra medical college & research institute sri ramachandra institute" : "sri ramachandra institute of higher education and research",
    "sri ramachandra institute of higher education and research(sriher)du" : "sri ramachandra institute of higher education and research",
    "sri ramachandra insititute of higher education and research" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra institute of higher education and research centre" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra institue of higher education and research" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra institute of higher education and research (sriher)" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra medical college sriramachandra institute of higher education and research" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra hospital" : "sri ramachandra medical college and hospital",
    "sri ramachandra medical college" : "sri ramachandra medical college and hospital",
    "sri ramachandra medical college & research institute" : "sri ramachandra medical college and hospital",
    "sri ramachandra hospital. (in patient ortho ward)" : "sri ramachandra medical college and hospital",
    "sri ramachandra college of physiotherapy ground out patient area" : "sri ramachandra medical college and hospital",
    "sri ramachandra hospital new opd faculty of physiotherapy" : "sri ramachandra medical college and hospital",
    "sri ramachandra faculty of physiotherapy sriher" : "sri ramachandra medical college and hospital",
    "sri ramachandra medical centre neurosurgery icu" : "sri ramachandra medical college and hospital",
    "research lab faculty of physiotherapy sri ramachandra institute of higher education and research" : "sri ramachandra insititute of higher education and research",
    "neonatology sri ramachandra university" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra university" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra medical centre" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra medical college and research institute" : "sri ramachandra insititute of higher education and research",
    "periodontology sri ramachandra university" : "sri ramachandra insititute of higher education and research",
    "sri ramachandra institute" : "sri ramachandra insititute of higher education and research",
    "jawaharlal institute of postgraduate medical education and research pondicherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education & research" : "jawaharlal institue of postgraduate medical education and research",
    "jipmer jawaharlal institute of post graduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical collage" : "jawaharlal nehru medical college",
    "jawaharlal institue of postgraduate medical education and research (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and research jipmer" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college kle university" : "jawaharlal nehru medical college",
    "jawaharlal nehru medical college belagavi" : "jawaharlal nehru medical college",
    "jawaharlal nehru medical college kle" : "jawaharlal nehru medical college",
    "jawaharlal nehru medical college and medical research centre" : "jawaharlal nehru medical college",
    "jawaharlal nehru homoeopathic medical college hospital" : "jawaharlal nehru homoeopathic medical college and hospital",
    "jawaharlal institute of post graduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru homoepathic medical college and hospital" : "jawaharlal nehru homoeopathic medical college and hospital",
    "jawaharlal institute of postgraduate medical education & research (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and research(jipmer) puducherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education& research" : "jawaharlal institue of postgraduate medical education and research",
    "department of neonatology women and childrens hospital jawaharlal institute" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education and research puducherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college & hospital a.m.u. aligarh" : "jawaharlal nehru medical college and hospital amu aligarh",
    "jawaharlal nehru institute of postgraduate medical education and research pondicherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college belgaum" : "jawaharlal nehru medical college",
    "jawaharlal institute of postgraduation medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru institute of postgraduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and research (jipmer) puducherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of medical education & research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college kle academy of higher education and research belagavi karnataka" : "jawaharlal nehru medical college",
    "rural service area under jawaharlal institute of postgraduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute" : "jawaharlal institue of postgraduate medical education and research",
    "rcc jawaharlal institute of postgraduate medical education and research puducherry" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college aligarh muslim university" : "jawaharlal nehru medical college and hospital aligarh muslim university",
    "jawaharlal institute of post-graduate medical education and research (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education & research (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education & research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical educaction and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and research institute" : "jawaharlal institue of postgraduate medical education and research",
    "anaesthesiology iind ot complex jawaharlal nehru medical college" : "jawaharlal nehru medical college",
    "jawaharlal institute of postgraduate medical education and research (jipmer) pondicherry" : "jawaharlal institue of postgraduate medical education and research",
    "acharya vinoba bhave rural hospital jawaharlal nehru medical college" : "jawaharlal nehru medical college",
    "iind ot complex jawaharlal nehru medical college" : "jawaharlal nehru medical college",
    "jawaharlal nehru medical college aligarh" : "jawaharlal nehru medical college and hospital amu aligarh",
    "jawaharlal nehru medical college & aligarh muslim university" : "jawaharlal nehru medical college and hospital amu aligarh",
    "jawaharlal nehru medical college and associated group of hospitals" : "jawaharlal nehru medical college",
    "jawaharlal institute of postgraduate medical education & research government of" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college and general hospital" : "jawaharlal nehru medical college",
    "jawaharlal institute of post-graduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education and research (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college and hospital aligarh muslim university aligarh" : "jawaharlal nehru medicine college and hospital amu aligarh",
    "jawaharlal institute of postgraduate medical education and reseach" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and research ( jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college and hospital aligarh muslim university aligarh" : "jawaharlal nehru medicine college and hospital amu aligarh",
    "jawaharlal nehru medical college & hospital aligarh muslim university aligarh uttar pradesh" : "jawaharlal nehru medicine college and hospital amu aligarh",
    "the jawaharlal institute of postgraduate medical education research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of post graduate medical education and research(jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "department of anesthesiology and critical care,jawaharlal nehru medical college and hospital" : "jawaharlal nehru medical college",
    "jawaharlal neheru main hospital and research centre" : "jawaharlal nehru medical college",
    "jawaharlal nehru medical college and attached hospital" : "jawaharlal nehru medical college",
    "kaher jawaharlal nehru medical college" : "jawaharlal nehru medical college",
    "jawaharlal institute of postgraduate medical education & reserach (jipmer)" : "jawaharlal institue of postgraduate medical education and research",
    "kle university jawaharlal nehru medical college" : "jawaharlal nehru medical college",
    "jawaharlal instittute of post graduate medical education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal nehru medical college a.m.u. aligarh" : "jawaharlal nehru medicine college and hospital amu aligarh",
    "jawaharlal institute of post graduate medical education and researc" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate education and research" : "jawaharlal institue of postgraduate medical education and research",
    "jawaharlal institute of postgraduate medical education and researcg" : "jawaharlal institue of postgraduate medical education and research",
    "regional ayurveda research institute for skin disorders ahmedabad (rarisd)" : "regional ayurveda research institute for skin disorders ahmedabad",
    "regional ayurveda research institute for skin disorders vijaywada" : "regional ayurveda research institute for skin disorders vijaywada",
    "regional ayurveda research institute-thiruvananthapuram" : "regional ayurveda research institute thiruvananthapuram",
    "veeda clinical research pvt. ltd" : "veeda clinical research pvt limited",
    "veeda clinical research pvt ltd" : "veeda clinical research pvt limited",
    "veeda clinical research ltd" : "veeda clinical research pvt limited",
    "veeda clinical research" : "veeda clinical research pvt limited",
    "vaidyaratnam p. s. variers arya vaidya sala kottakkal charitable hospital" : "vaidyaratnam p s varier ayurveda college",
    "vaidyaratnam p. s. varier ayurved college kottakkal" : "vaidyaratnam p s varier ayurveda college",
    "vaidyaratnam ps varier ayurveda college hosptial kottakkal" : "vaidyaratnam p s varier ayurveda college",
    "sarvodaya hospital & research centre" : "sarvodaya hospital and research centre",
    "command hospital cc" : "command hospital (cc)",
    "command hospital southern command" : "command hospital (southern command)",
    "command hospital air force" : "command hospital airforce",
    "armed forces medical college and command hospital (sc) wanowrie" : "command hospital sc",
    "command hospital (sc) afmc" : "command hospital sc",
    "command hospital (sc)" : "command hospital sc",
    "afmc command hospital southern command" : "command hospital southern command",
    "armed forces medical college command hospital southern command" : "command hospital southern command",
    "operation theatre complex dept of anaesthesiology command hospital southern command" : "command hospital southern command",
    "command hospital southern command pune & military hospital" : "command hospital southern command",
    "new command hospital southern command" : "command hospital southern command",
    "maharishi markandeshwar institude of physiotherapy and rehabilitation" : "maharishi markandeshwar institute of physiotherapy and rehabilitation",
    "maharishi markandeshwar institute of medical science and research" : "maharishi markandeshwar institute of medical sciences and research",
    "maharishi markandeshwar institute of medical science and research" : "maharishi markandeshwar institute of medical sciences and research",
    "maharishi markandeshwar (deemed to be university)" : "maharishi markandeshwar deemed university",
    "maharishi markandeshwer deemed university" : "maharishi markandeshwar deemed university",
    "maharishi markandeshwar deemed to be university mullana" : "maharishi markandeshwar deemed university",
    "maharishi markandeshwar college of dental sciences & research mmu" : "maharishi markandeshwar college of dental science and research",
    "maharishi markandeshwar college of dental sciences" : "maharishi markandeshwar college of dental science and research",
    "maharishi markandeshwar superpseciality hospital (ipd)" : "maharishi markandeshwar super speciality hospital",
    "maharishi markandeshwar super specialty hospital" : "maharishi markandeshwar super speciality hospital",
    "maharishi markandeshwar superspeciality hospital" : "maharishi markandeshwar super speciality hospital",
    "maharishi markandeshwar institute of physiotherapy and rehabilitation mullana ambala haryana" : "maharishi markandeshwar institute of physiotherapy and rehabilitation",
    "maharishi markandeshwar institute of physiotherapy" : "maharishi markandeshwar institute of physiotherapy and rehabilitation",
    "sports lab maharishi markandeshwar institute of physiotherapy and rehabilitation" : "maharishi markandeshwar institute of physiotherapy and rehabilitation",
    "maharishi markandeshwar hospital department of musculoskeletal physiotherapy" : "maharishi markandeshwar hospital",
    "maharishi markandeshwar hospital department of neurological physiotherapy" : "maharishi markandeshwar hospital",
    "maharishi markandeshwar hospital department of of musculoskeletal physiotherapy" : "maharishi markandeshwar hospital",
    "maharishi markandeshwar institute of medical sciences and research centre mullana-ambala" : "maharishi markandeshwar institute of medical sciences and research",
    "maharishi markandeshwar institute of medical sciences and research hospital" : "maharishi markandeshwar institute of medical sciences and research",
    "maharishi markandeshwar institute of medical sciences and research mullana" : "maharishi markandeshwar institute of medical sciences and research",
    "sdm college of ayurveda and hospital hassan" : "sdm college of ayurveda and hospital",
    "sdm college of ayurveda and hospital kuthpady" : "sdm college of ayurveda and hospital",
    "sdm college of ayurveda and hospital hassan karnataka" : "sdm college of ayurveda and hospital",
    "department of agada tantra sdm college of ayurveda and hospital" : "sdm college of ayurveda and hospital",
    "government ayurveda medical college bangalore & sdm college of ayurveda kuthpady" : "sdm college of ayurveda and hospital",
    "sdm college of ayurveda and hospital opd and ipd" : "sdm college of ayurveda and hospital",
    "sdm college of ayurveda udupi karnataka" : "sdm college of ayurveda and hospital",
    "sdm college of ayurveda hospital hassan" : "sdm college of ayurveda and hospital",
    ". of manas roga opd number sdm college of ayurveda and hospital hassan" : "sdm college of ayurveda and hospital",
    "l v prasad eye institute bhubaneswar campus" : "l v prasad eye institute bhubaneswar",
    "charak hospital and research center" : "charak hospital and research centre",
    "drs sudha and nageswararao siddhartha institute of dental sciences gannavaram" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "drs sudha ad nageswararao siddhartha institute of dental sciences gannavaram" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "drs sudha and nageswararo siddhartha institute of dental sciences" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "drs sudha and nageswar rao siddhartha institute of dental sciences" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "drs sudha and nageswara rao institute of dental sciences" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "drs sudha and nageswararao siddhartha institute of dental sciences" : "drs sudha and nageswara rao siddhartha institute of dental sciences",
    "shubham sudbhawana superspeciality hospital" : "shubham sudbhawana super speciality hospital",
    "shubham multi speciality hospital ahmedabad gujarat" : "shubham multispeciality hospital",
    "aig hospital" : "aig hospitals",
    "aig hospitals (a unit of asian institute of gastroenterology)" : "aig hospitals",
    "aig hospitals institute of cardiac sciences and research" : "aig hospitals",
    "aig hospitals gachibowli" : "aig hospitals",
    "asian institute of gastroenterology/aig hospitals" : "aig hospitals",
    "rajiv gandhi cancer institute & research center" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute and research centre rohini" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi ayurvedic college" : "rajiv gandhi ayurvedic college and hospital",
    "rajiv gandhi cancer institute" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute & research centre" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute & research centre (rgci)" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute and research" : "rajiv gandhi cancer institute and research centre",
    "mri department rajiv gandhi cancer institute and research centre" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer hospital" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute and research center sec rohini" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi cancer institute and research centre sector rohini" : "rajiv gandhi cancer institute and research centre",
    "rajiv gandhi government post graduate ayurvedic college paprola district kangra himachal pradesh" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "rajiv gandhi government post graduate ayurvedic" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "rajiv gandhi government post graduate ayurvedic hospital" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "rajiv gandhi government post graduate ayurvedic college and hospital" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "rajiv gandhi government post-graduate ayurvedic college" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "rajiv gandhi government general hospital and madras medical college" : "rajiv gandhi government general hospital",
    "rajiv gandhi government post graduate ayurvedic college paprola district kangra himachal pradesh" : "rajiv gandhi government postgraduate ayurvedic college and hospital",
    "shettyÃ¢â‚¬â„¢s hospital" : "shettys hospital",
    "a b shetty memorial institute of dental sciences" : "a.b.shetty memorial institute of dental sciences",
    "ground a b shetty memorial institute of dental sciences" : "a.b.shetty memorial institute of dental sciences",
    "ab shetty memorial institute of dental sciences" : "a.b.shetty memorial institute of dental sciences",
    "a.b shetty memorial institute of dental science" : "a.b.shetty memorial institute of dental sciences",
    "department a b shetty memorial institute of dental sciences" : "a.b.shetty memorial institute of dental sciences",
    "sri jayadeva institute of cardiovascular sciences and research jayanagar 9th bannerghatta road" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute of cardiovascular sciences and reaserch" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute of cardiology" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute of cardiovascular sciences and research mysore" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute of cardiovascular sciences & research" : "sri jayadeva institute of cardiovascular sciences and research",
    "sri jayadeva institute of cardiac research" : "sri jayadeva institute of cardiovascular sciences and research",
    "pradyumna bal memorial hospital kalinga institute of medical sciences" : "pradyumna bal memorial hospital",
    "pradyumna bal memorial hospital kims" : "pradyumna bal memorial hospital",
    "pradyumna bala memorial hospital" : "pradyumna bal memorial hospital",
    "physical rehabilitation department faculty of physiotherapy" : "physical rehabilitation department",
    "sgt dental college hospital and research institute sgt university gurugram haryana" : "sgt dental college hospital and research institute",
    "sgt dental college hospital & research institute" : "sgt dental college hospital and research institute",
    "sgt dental college" : "sgt dental college hospital and research institute",
    "sgt dental hospital" : "sgt dental college hospital and research institute",
    "sgt dental college and research institute" : "sgt dental college hospital and research institute",
    "medical college and ssg hospital baroda" : "ssg hospital baroda",
    "oral and maxillofacial surgery (cder) aiims" : "oral and maxillofacial surgery cder aiims",
    "oral and maxillofacial surgery dr. d. y. patil dental college and hospital" : "oral and maxillofacial surgery department dr. d. y. patil dental college & hospital",
    "antenatal ward antenatal opd labour wch in jipmer" : "jipmer",
    "jawaharlal institute of postgraduate medical education and research(jipmer)" : "jipmer",
    "jipmer pondicherry" : "jipmer",
    "radiation oncology department jipmer" : "jipmer",
    "jawaharlal institute of postgraduate medical education and research (jipmer)" : "jipmer",
    "jipmer hospital" : "jipmer",
    "jipmer puducherry" : "jipmer",
    "ent opd jipmer" : "jipmer",
    "jipmer campus rd gorimedu dhanvantari nagar,puducherrypondicherrypondicherry" : "jipmer",
    "urban field practice area of jipmer pondicherry pondicherrypondicherry" : "jipmer",
    "jipmer jawaharlal institute of post graduate medical education and research" : "jipmer",
    "luqman unani medical college hospital & research centre" : "luqman unani medical college hospital and research center",
    "luqman unani medical college hospital and research centre" : "luqman unani medical college hospital and research center",
    "moalajat opd no. ground luqman unani medical college hospital and research center" : "luqman unani medical college hospital and research center",
    "luqman unani medical hospital" : "luqman unani medical college hospital and research center",
    "luqman unani medical college hospital" : "luqman unani medical college hospital and research center",
    "luqman unani medical college hospital and research centre naubag vijayapura" : "luqman unani medical college hospital and research center",
    "luqman unani and medical college and hospital and research centre" : "luqman unani medical college hospital and research center",
    "luqman unani hospital" : "luqman unani medical college hospital and research center",
    "uttara adhunik medical college" : "uttara adhunik medical college and hospital",
    "jyoti multispecialty clinic" : "jyoti multispeciality clinic",
    "sunad ayurveda chinchwad" : "sunad ayurved",
    "acpm dental college and hospital" : "jmfs acpm dental college dhule",
    "acpm dental college dhule" : "jmfs acpm dental college dhule",
    "jmfs acpm dental college" : "jmfs acpm dental college dhule",
    "acpm medical college and hospital" : "jmfs acpm dental college dhule",
    "acpm dental college" : "jmfs acpm dental college dhule",
    "conservative dentistry and endodontics acpm dental college" : "jmfs acpm dental college dhule",
    "physical medicine and rehabilitation no: st.johns medical college" : "st.johns medical college & hospital",
    "st.johns medical college hospital" : "st.johns medical college & hospital",
    "st.johns medical college" : "st.johns medical college & hospital",
    "st.johns college hospial" : "st.johns medical college & hospital",
    "cardiology st.johns medical college hospital" : "st.johns medical college & hospital",
    "bharati vidyapeeth deemed university college of ayurved" : "bharati vidyapeeth (deemed to be) university college of ayurved dhankawadi",
    "bharati vidyapeeth deemed university medical college and hospital" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth(deemed to be university) college of ayurved and hospital" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth (deemed to be university) college of ayurved and hospital" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth deemed (to be) university college of ayurved" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth deemed to be university college of ayurved" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth college of ayurveda and hospital deemed to be university" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth deemed to be university college of ayurved and hospita" : "bharati vidyapeeth (deemed to be university) medical college & hospital",
    "bharati vidyapeeth ( deemed to be university)homoeopathic medical college and hospital" : "bharati vidyapeeth (deemed to be) university college of ayurved dhankawadi",
    "bharati vidyapeeth (deemed to be university) college of ayurved and hospita" : "bharati vidyapeeth (deemed to be) university college of ayurved dhankawadi",
    "bharati vidyapeeth deemed to be university college of ayurveda and hospital" : "bharati vidyapeeth (deemed to be) university college of ayurved dhankawadi",
    "bharati vidyapeeth(deemed to be university)college of ayurved and hospital dhanakawadi" : "bharati vidyapeeth (deemed to be) university college of ayurved dhankawadi",
    "bharati vidyapeeth college of ayirved and hospital" : "bharati vidyapeeth college of ayurved and hospital",
    "bharati vidyapeeth?s medical college & hospital" : "bharati vidyapeeth medical college",
    "pediatrics bharati vidyapeeth medical college" : "bharati vidyapeeth medical college",
    "bharati vidyapeeth medical foundations ayurved hospital" : "bharati vidyapeeth medical foundation ayurved hospital",
    "bharati vidyapeeth medical foundation ayurved hospital" : "bharati vidyapeeth medical foundations college of ayurved and hospital",
    "bakson homeopathic medical college & hospital" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college and hospital . central reseach institute of homeopathy" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college & hospital . central research of homoeopathy" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college and hospital" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college hospital" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college" : "bakson homeopathic medical college and hospital",
    "bakson homoeopathic medical college &hospital" : "bakson homeopathic medical college and hospital",
    "mahatma gandhi ayurved college hospital and research centre salod h wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod (h) wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod(h) wardha maharashtra" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurvedic college hospital and research center salod wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research center salod (h) wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research center salod wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod hirapur wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "departmmahatma gandhi ayurved college hospital and research centre salod hirapur" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod (h)" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod wardha" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "mahatma gandhi ayurved college hospital and research centre salod" : "mahatma gandhi ayurved college hospital and research centre salod (h)",
    "corps coordinated through office of the addl. director general armed forces medical services (mr)" : "corps coordinated through office of addl. director general armed forces medical services (mr)",
    "armed forces medical college and command hospital (sc) wanowrie" : "armed forces medical college and command hospital (sc) wanowarie",
    "o.p.d and ipd of all institute of ayurveda" : "all institute of ayurveda",
    "all institute of ayurved" : "all institute of ayurveda",
    "hospital all institute of ayurveda" : "all institute of ayurveda",
    "mahajan clinic" : "dr. mahajan clinic",
    "madras diabetes research foundation (mdrf)" : "madras diabetes research foundation (mdrf) & dr.mohans diabetes specialities centre",
    "narayana dental college nd hospital" : "narayana dental college and hospital",
    "narayana dental colllege and hospital" : "narayana dental college and hospital",
    "oral medicine and radiology dept narayana dental college" : "oral medicine and radiology narayana dental college"
}

 


# Function to clean names
def clean_name(name):
    if pd.isna(name):
        return name
    name_lower = str(name).lower()
    for keyword, replacement in replacements.items():
        if keyword in name_lower:
            return replacement
    return name

# Apply cleaning
df["Name of Site"] = df["Name of Site"].apply(clean_name)

# Save updated CSV in same folder
df.to_csv(os.path.join(folder_path, "Standardize_Site_Name_Cleaned_updated.csv"), index=False)

print("✅ Cleaning complete. Saved as 'Standardize_Site_Name_Cleaned_updated.csv'")
